In [4]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [1,2,3]])
b = np.array([2,3,4])


In [6]:
a@b.T

array([20, 20])

In [10]:
import joblib as jb

df = jb.load(r'/workspaces/miniconda/PK-Analysis/logs/check_test__10__50.jb')

In [8]:
df

{'x': array([-0.49522929,  0.70356423, -0.00548798,  0.00941784, -0.0038467 ]),
 'iteration': 5}

In [11]:
np.exp(df['x'])

array([0.77297971, 2.09651605, 1.02451358, 1.02622523, 0.97818713])

In [9]:
np.exp(df['x'])

array([0.60943115, 2.020943  , 0.99452705, 1.00946233, 0.99616068])

In [26]:
df

d                                          train_idx  \
0   1.250000  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
1   1.272414  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
2   1.294828  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
3   1.317241  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
4   1.339655  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
5   1.362069  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
6   1.384483  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
7   1.406897  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
8   1.429310  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
9   1.451724  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
10  1.474138  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
11  1.496552  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
12  1.518966  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
13  1.541379  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
14  1.563793  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
15  1.586207  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
16  1.608621  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
17  1.631034  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
18  1.653448  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   

                                             test_idx  \
0   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
1   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
2   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
3   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
4   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
5   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
6   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
7   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
8   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
9   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
10  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
11  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
12  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
13  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
14  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
15  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
16  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
17  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
18  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   

                                             cv_error  avg_cv_error  
0   [29.01421, 34.900204, 39.70578, 38.237083, 31....     33.405560  
1   [27.16982, 34.900204, 30.523855, 38.237083, 31...     30.697897  
2   [26.984943, 34.900204, 39.70578, 34.099102, 36...     32.708225  
3   [33.417225, 34.900204, 39.70578, 38.237083, 31...     34.436962  
4   [27.16982, 24.701466, 39.70578, 28.785814, 30....     29.894611  
5   [27.16982, 34.900204, 27.767008, 38.237083, 30...     30.905359  
6   [26.984943, 34.900204, 39.70578, 36.79276, 36....     33.637928  
7   [26.984943, 34.900204, 39.70578, 38.237083, 36...     32.309414  
8   [33.417225, 34.900204, 36.70317, 38.237083, 36...     34.037769  
9   [26.984943, 24.701466, 39.70578, 38.237083, 30...     32.994743  
10  [33.417225, 24.701466, 39.70578, 35.67656, 36....     34.496658  
11  [26.984943, 24.701466, 29.470985, 38.237083, 3...     30.668919  
12  [33.417225, 22.001179, 39.70578, 38.237083, 35...     31.684940  
13  [26.984943, 34.900204, 39.70578, 34.099102, 36...     31.942585  
14  [26.984943, 24.701466, 39.70578, 38.237083, 36...     31.656681  
15  [26.984943, 34.900204, 30.523855, 38.237083, 3...     33.047501  
16  [26.984943, 34.900204, 39.70578, 38.237083, 36...     33.221077  
17  [26.984943, 34.900204, 39.70578, 38.237083, 30...     32.938461  
18  [26.984943, 24.701466, 39.70578, 34.099102, 36...     32.261131

In [22]:
df

d                                          train_idx  \
0   1.000000  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
1   1.051724  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
2   1.103448  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
3   1.155172  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
4   1.206897  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
5   1.258621  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
6   1.310345  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
7   1.362069  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
8   1.413793  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
9   1.465517  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
10  1.517241  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
11  1.568966  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
12  1.620690  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
13  1.672414  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
14  1.724138  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
15  1.775862  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
16  1.827586  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
17  1.879310  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
18  1.931034  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
19  1.982759  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   

                                             test_idx  \
0   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
1   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
2   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
3   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
4   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
5   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
6   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
7   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
8   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
9   [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
10  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
11  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
12  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
13  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
14  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
15  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
16  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
17  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
18  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
19  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   

                                             cv_error  avg_cv_error  
0   [26.984943, 34.900204, 39.70578, 38.237083, 36...     33.685692  
1   [26.984943, 34.900204, 39.70578, 38.237083, 30...     32.652187  
2   [26.984943, 34.900204, 39.70578, 37.09716, 36....     33.839256  
3   [26.984943, 24.701466, 39.70578, 38.237083, 36...     32.262283  
4   [26.1211, 34.900204, 39.70578, 38.237083, 36.4...     33.963284  
5   [26.984945, 34.900204, 28.166233, 38.237087, 3...     32.799294  
6   [26.984943, 34.900204, 39.70578, 38.237083, 36...     32.133324  
7   [27.16982, 34.900204, 27.767008, 38.237083, 30...     30.905359  
8   [26.984943, 24.701466, 29.470985, 36.79276, 36...     30.442453  
9   [26.984943, 34.900204, 29.470985, 38.23709, 31...     30.876129  
10  [26.984943, 22.001179, 39.70578, 38.237083, 36...     31.499710  
11  [26.984943, 34.900204, 39.70578, 38.237083, 35...     33.483688  
12  [26.984943, 34.900204, 39.70578, 36.79276, 30....     31.370499  
13  [26.984943, 24.701466, 39.70578, 38.237083, 36...     32.099129  
14  [33.417225, 34.900204, 39.70578, 38.237083, 36...     34.844826  
15  [27.16982, 24.701466, 29.470985, 34.099102, 31...     31.118839  
16  [26.984943, 24.701466, 30.523855, 36.79276, 36...     30.595104  
17  [26.984943, 34.900204, 39.70578, 34.099102, 36...     32.153381  
18  [26.984943, 34.900204, 39.70578, 38.237083, 36...     33.023708  
19  [

In [8]:
df

d                                          train_idx  \
0  1.000000  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
1  1.444444  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
2  1.888889  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
3  2.333333  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
4  2.777778  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
5  3.222222  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
6  3.666667  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
7  4.111111  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
8  4.555556  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
9  5.000000  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   

                                            test_idx  \
0  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
1  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
2  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
3  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
4  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
5  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
6  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
7  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
8  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   
9  [[163, 164, 165, 166, 167, 168, 169, 170, 171,...   

                                            cv_error  avg_cv_error  
0  [26.984924, 34.900196, 39.70578, 34.09926, 36....     33.281013  
1  [26.984924, 34.900196, 29.471006, 34.09926, 36...     30.919113  
2  [26.984924, 33.393, 39.70578, 38.237087, 30.45...     32.632072  
3  [27.169912, 24.701462, 39.70578, 38.237087, 36...     33.182461  
4  [33.41736, 22.001156, 30.523914, 38.237087, 30...     31.792606  
5  [33.41736, 34.900196, 39.70578, 38.237087, 36....     34.542309  
6  [27.169912, 34.900196, 39.70578, 36.792797, 36...     33.546104  
7  [29.014349, 34.900196, 39.70578, 38.237087, 36...     33.897739  
8  [33.41736, 22.359377, 39.70578, 33.828873, 36....     32.643135  
9  [26.984924, 34.900196, 39.70578, 38.237087, 30...     34.222145

In [3]:
df

d                                          train_idx  \
0  1.000000  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
1  1.444444  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
2  1.888889  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
3  2.333333  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   
4  2.777778  [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13...   

                                            test_idx  \
0  [[106, 107, 108, 109, 110, 111, 112, 113, 114,...   
1  [[106, 107, 108, 109, 110, 111, 112, 113, 114,...   
2  [[106, 107, 108, 109, 110, 111, 112, 113, 114,...   
3  [[106, 107, 108, 109, 110, 111, 112, 113, 114,...   
4  [[106, 107, 108, 109, 110, 111, 112, 113, 114,...   

                                            cv_error  avg_cv_error  
0  [31.106936, 38.989567, 33.588657, 36.85335, 28...     33.739056  
1  [31.106936, 32.267445, 33.588657, 33.111217, 2...     31.646206  
2  [31.106936, 32.267445, 33.588657, 33.111217, 2...     31.646206  
3  [25.884426, 38.989567, 33.588657, 33.111217, 2...     31.946127  
4  [31.106936, 38.989567, 33.588657, 36.85335, 28...     33.739056

In [12]:
df['cv_error'][0]

[17.57735850551117,
 20.161468183002683,
 15.775907160652936,
 19.41445153500867,
 18.28495725850634]